spring:
  application:
    name: spring-ai-vision
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        #model: hf.co/bartowski/ibm-granite_granite-vision-3.2-2b-GGUF
        #model: llava
        model: minicpm-v
        #model: moondream
      embedding:
        model: mxbai-embed-large
